#include <stdio.h>
#include <stdint.h>

typedef enum _ETYPE_SUCCESS
{
    BXR_SUCCESS = 0,
    BXR_CHANGE_POLICY,
    BXR_UPDATE_VERSION,
    BXR_ROLLBACK_VERSION,
    BXR_UPLOADED_VERSION,
    BXR_NONE_USER,
    BXR_MULTI_USER,
    BXR_CHANGE_USER

}ETYPE_SUCCESS;

typedef enum _ETYPE_ERROR
{
    BXR_SOCKET_ERR = 1,
    BXR_DIAL_ERR,
    BXR_REQUEST_ERR,
    BXR_REPLY_ERR,
    BXR_MESSAGE_SIZE_ERR,
    BXR_CONF_CREATE_ERR,
    BXR_CONF_PARSE_ERR,
    BXR_CONF_UPDATE_ERR,
    BXR_CONF_SET_ERR,
    BXR_CONF_NONE_ERR,
    BXR_CONF_ERR,
    BXR_POLICY_CREATE_ERR,
    BXR_POLICY_READ_ERR,
    BXR_POLICY_PARSE_ERR,
    BXR_POLICY_NONE_ERR,
    BXR_POLICY_MEMORY_ERR,
    BXR_DFPOLICY_NONE_ERR,
    BXR_POLICY_ERR,
    BXR_FILE_OPEN_ERR,
    BXR_FILE_MOVE_ERR,
    BXR_PSFILE_NONE_ERR,
    BXR_PSFILE_MEMORY_ERR,
    BXR_PSFILE_READ_ERR,
    BXR_PWFILE_READ_ERR,
    BXR_PWFILE_NONE_ERR,
    BXR_PWFILE_MEMORY_ERR,
    BXR_FOLDER_OPEN_ERR,
    BXR_DB_OPEN_ERR,
    BXR_DB_EXECUTION_ERR,
    BXR_DB_ERR,
    BXR_REGEX_COMPILE_ERR,
    BXR_REGEX_EXECUTION_ERR,
    BXR_HEARBEAT_THREAD_ERR,
    BXR_SENSITIVE_THREAD_ERR,
    BXR_WARNING_THREAD_ERR,
    BXR_WEBVIEW_ERR,
    BXR_DATA_FREQUENT_ERR,
    BXR_GET_HOMEPATH_ERR,
    BXR_UUID_NONE_ERR,
    BXR_COMPARE_DATE_ERR,
    BXR_LASTPLAN_CREATE

}ETYPE_ERROR;